    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      maven_build:
        name: Maven build
        runs-on: ubuntu-latest
        steps:
          - name: checkout your code
            uses: actions/checkout@v2
          - name: Set up JDK 1.8
            uses: actions/setup-java@v1
            with:
              java-version: 1.8
          - name: Cache Maven packages
            uses: actions/cache@v1
            with:
              path: ~/.m2
              key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
              restore-keys: ${{ runner.os }}-m2
          - name: Build with Maven
            run: mvn -B package --file pom.xml
          - run: mkdir -p staging/lib && cp target/*.jar staging  && cp target/lib/*.jar staging/lib
          - uses: actions/upload-artifact@v1
            with:
              name: target
              path: staging
      build:
        needs: [maven_build]
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - name: Setup student pandora.jar
            uses: actions/download-artifact@v1
            with:
              name: target
          - name: Downloading testSuite
            run: wget https://github.com/Estia-advanced-programming/test-generator/raw/master/dist/testSuite.zip
          - name: unzip
            run: unzip testSuite.zip ; mv staging testSuite
          - name: Downloading autograding configuration
            run:  wget https://github.com/Estia-advanced-programming/test-generator/raw/master/dist/autograding.json -P .github/classroom
          - name: Downloading reference pandora
            run:  wget https://github.com/Estia-advanced-programming/test-generator/raw/master/dist/pandora.jar -O target/referencePandora.jar
          - uses: education/autograding@beta
          - name: publish report
            if: always()
            uses: actions/upload-artifact@v1
            with:
              name: testReport
              path: __autograding/result.txt
