name: Import issues from Template

on:
  project:
    created:

jobs:
  copy-issues:
    #Prevent execution on template repository, only run once
    if: github.run_number == '1'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download git mover
      run: wget -q https://raw.githubusercontent.com/ahadik/git_mover/master/git-mover.py
    - name: setup dependencies
      run: pip -q install requests argparse
    - name: Copy issues from template
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SOURCE: Estia-advanced-programming/pandora-template
        DESTINATION: ${{ github.repository }}
        ACTOR: ${{ github.actor }}
      run: python git-mover.py -iml -dt $TOKEN $ACTOR $TOKEN $SOURCE $DESTINATION
  remove-setup:
    #Prevent execution on template repository, wait third commit
    if: github.run_number == '1'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Remove assignement-setup.yml
      run: |
        rm .github/workflows/assignement-setup.yml
    - name: replace classroom.yml
      run: |
        mv .github/estia/classroom.yml .github/workflows/classroom.yml
    - name: Commit files
      run: |
        git config --local user.name $GITHUB_ACTOR
        git commit -m "Update autograding" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
